CREATE TABLE Ticket.dbo.Users (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID()
    , Name VARCHAR(150) NOT NULL
    , Email VARCHAR(150) NOT NULL
    , Phone VARCHAR(15) NULL
    , BirthDate Datetime NULL
);

CREATE TABLE Ticket.dbo.Address
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID()
    , UserId UNIQUEIDENTIFIER NOT NULL
    , ZipCode VARCHAR(9) NOT NULL
    , Category VARCHAR(14) NOT NULL
    , Street VARCHAR(150) NULL
    , Complement VARCHAR(150) NULL
    , Neighborhood VARCHAR(50) NULL
    , City VARCHAR(50) NULL
    , State VARCHAR(50) NULL
    , Ibge VARCHAR(15) NULL
    , Gia VARCHAR(15) NULL
    , Ddd VARCHAR(15) NULL
    , Siafi VARCHAR(15) NULL
);


ALTER TABLE Address
	ADD CONSTRAINT FK_USER_ADDRESS FOREIGN KEY (UserId)
	REFERENCES Users (Id)
	ON DELETE CASCADE
    ON UPDATE CASCADE;

